# Generated by Django 4.2.16 on 2025-04-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_blogtype_alter_blog_image_alter_blog_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogtype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogtype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blogtype',
            name='title',
        ),
        migrations.RemoveField(
            model_name='blogtype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='blogtype',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='blogtype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
