# Generated by Django 4.2.16 on 2025-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(default='Hello', max_length=254),
            preserve_default=False,
        ),
    ]
