# Generated by Django 4.2.16 on 2025-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='types',
            field=models.ManyToManyField(related_name='blogs', to='blog.blogtype'),
        ),
    ]
